repetitor/repetitor/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from webrepetitor.sitemaps import BdSitemap

sitemaps = {'posts': BdSitemap}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webrepetitor.urls')),
    path('webrepetitor/', include('webrepetitor.urls', namespace='webrepetitor')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')


]

repetitor/webrepetitor/urls.py
from django.urls import path
from . import views

app_name = 'webrepetitor'

urlpatterns = [
    # Домашняя страница
    path('', views.main_page, name='main_page'),
    # Страница со списком информации о репетиторе
    path('rubrik', views.rubrik, name='rubrik'),
    path('haracteristic', views.haracteristic, name='haracteristic'),
    path('price', views.price, name='price'),
    path('predmet', views.predmet, name='predmet'),
    # Страница для электронной почты
    path('share', views.post_share, name='share'),
    path('<int:id>/', views.post_detail, name='post_detail'),

]

repetitor/webrepetitor/models.py
from django.db import models
from django.urls import reverse




class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Bd.Status.PUBLISHED)


class Bd(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Черновик'
        PUBLISHED = 'PF', 'Опубликовано'
    # Заголовок
    title = models.CharField(max_length=250)
    # Короткая метка
    slag = models.SlugField(max_length=250)
    # Сам текст, описание информации
    content = models.TextField()
    # Цена, вещественное число
    price = models.FloatField()
    # Присваиваем текущую дату и время записи. Индекс для сортировки даты по убыванию.
    published_time = models.DateTimeField(auto_now_add=True, db_index=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    # Опубликованные рубрики
    rubric = models.ForeignKey('Rubric', null=True,
                               on_delete=models.PROTECT, verbose_name='Рубрика')

    objects = models.Manager()
    # Менеджер, который позволяет извлекать посты
    published = PublishedManager()

    def __str__(self):
        return f'{self.title} - {self.content}'

    def get_absolute_url(self):
        return reverse('webrepetitor:main_page', args=[self.id])



class Rubric(models.Model):
    name = models.CharField(max_length=50, db_index=True, verbose_name='Название')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Рубрики'
        verbose_name = 'Рубрика'
        ordering = ['name']

repetitor/webrepetitor/forms.py
from django import forms

class EmailPostForm(forms.Form):
    # Имя чел отправляющего сообщение
    name = forms.CharField(max_length=25)
    # Адрес эл почты отправляющего чел
    email = forms.EmailField()
    # Адрес эл почты получателя
    to = forms.EmailField()
    # Комментарии, которые будут вставлятся в эл письмо
    comments = forms.CharField(required=False, widget=forms.Textarea)

repetitor/webrepetitor/views.py
from django.shortcuts import render, get_object_or_404
from .models import Bd, Rubric
from django.core.paginator import Paginator
from .forms import EmailPostForm
from django.core.mail import send_mail



def main_page(request):
    """Домашняя страница сайта"""
    posts = Bd.objects.all()
    rubrics = Rubric.objects.all()
    # Постраничная разбивка
    paginator = Paginator(posts, 1)
    page_nam = request.GET.get('page', 1)
    page = paginator.get_page(page_nam)
    context = {'rubrics': rubrics, 'page': page, 'posts': page.object_list}
    return render(request, 'webrepetitor/main_page.html', context)



def rubrik(request):
    """Информация о рубриках"""
    posts = Bd.published.all()
    rubrics = Rubric.objects.all()
    return render(request, 'webrepetitor/rubrici.html', {'posts': posts, 'rubrics': rubrics})


def haracteristic(request):
    """Характеристика"""
    bbs = Bd.published.all().filter(id=6)
    return render(request, 'webrepetitor/haracteristic.html', {'bbs': bbs})


def price(request):
    """Цены"""
    bbs = Bd.objects.all()
    rubrics = Rubric.objects.all()
    context = {'bbs': bbs, 'rubrics': rubrics}
    return render(request, 'webrepetitor/price.html', context)


def predmet(request):
    """Предметы преподавания"""
    bbs = Bd.objects.all().order_by('id')[:2]
    return render(request, 'webrepetitor/predmet.html', {'bbs': bbs})


def post_share(request):
    # Извлечь пост по id
    post = Bd.published.all()
    sent = False
    if request.method == 'POST':
        # Форма была передана на обработку
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Поля формы прошли валидацию
            cd = form.cleaned_data
            # ....отправить электронное письмо
            subject = f"{cd['name']} recommends you read"\
            f" {post.title}"

            message = f"Read {post.title} \n\n" \
            f" {cd['name']}\ comments: {cd['comments']}"

            send_mail(subject, message, 'spriteverdar777@gmail.com',
                      [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'webrepetitor/share.html', {'post': post, 'form': form, 'sent': sent})


def post_detail(request, id):
    post = get_object_or_404(Bd, id=id, status=Bd.Status.PUBLISHED)
    return render(request, 'webrepetitor/detail.html', {'post': post})

repetitor/webrepetitor/templates/webrepetitor/base.html
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
        <span class="fs-4"><ya-tr-span data-index="1-0" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="Pricing example" data-translation="Главная" data-ch="0" data-type="trSpan">На главную</ya-tr-span></span>
      </a>

      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'webrepetitor:haracteristic' %}"><ya-tr-span data-index="2-0" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="Features" data-translation="Характеристики" data-ch="0" data-type="trSpan">Обо мне</ya-tr-span></a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'webrepetitor:predmet' %}"><ya-tr-span data-index="3-0" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="Enterprise" data-translation="Предметы" data-ch="0" data-type="trSpan">Предметы</ya-tr-span></a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'webrepetitor:rubrik' %}"><ya-tr-span data-index="4-0" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="Support" data-translation="Рубрики" data-ch="0" data-type="trSpan">Рубрики</ya-tr-span></a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'webrepetitor:price' %}"><ya-tr-span data-index="5-0" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="Pricing" data-translation="Цены" data-ch="0" data-type="trSpan">Цены</ya-tr-span></a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'webrepetitor:share' %}"><ya-tr-span data-index="5-0" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="Contact" data-translation="Контакты" data-ch="0" data-type="trSpan">Контакты</ya-tr-span></a>

      </nav>

    </div>

    {% block content %}{% endblock %}


</body>

repetitor/webrepetitor/templates/webrepetitor/detail.html
{% extends "webrepetitor/base.html" %}


{% block title %}{{ post.title }}{% endblock %}

{% block content %}
 <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
 <div class="alert alert-warning mt-2">
  <h1>{{ post.title }}</h1>
  <p class="date">
     {{post.content}}
  </p>
  {{ post.body|linebreaks }}
</div>
{% endblock %}

repetitor/webrepetitor/templates/webrepetitor/haracteristic.html
{% extends 'webrepetitor/base.html' %}

{% block title %}
    Обо мне
{% endblock %}


{% block content %}
<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal text-body-emphasis">Обо мне</h1>
           {% for post in bbs %}
                <div class="alert alert-warning mt-2">
                <a href="{% url 'webrepetitor:post_detail' post.id %}">
          <p class="date">{{ post.title }}
            </p>
            {{ post.body|truncatewords_html:30|linebreaks }}

        </div>
        {% endfor %}
{% endblock %}

repetitor/webrepetitor/templates/webrepetitor/main_page.html
{% extends 'webrepetitor/base.html' %}
{% block title %}
{% load static %}
    Главная страница
{% endblock %}

{% block content %}

    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal text-body-emphasis">Преподаватель Вероника Игоревна</h1>
      <p class="fs-5 text-body-secondary"><ya-tr-span data-index="6-0" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="Quickly build an effective pricing table for your potential customers with this Bootstrap example. " data-translation="Качественная подача материала - один из главных факторов для восприятия. " data-ch="0" data-type="trSpan">Качественная подача материала - один из главных факторов для восприятия. </ya-tr-span><ya-tr-span data-index="6-1" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="Постороение занятия с использованием научного подхода к клиенту" data-translation="Постороение занятия с использованием научного подхода к клиенту" data-ch="0" data-type="trSpan">Постороение занятия с использованием научного подхода к клиенту.</ya-tr-span></p>
        <img src="static/webrepetitor/bs.jpg" alt="Телеграмм"></a>">
    {% for post in posts %}

        <div class="alert alert-warning mt-2">
    <h2>
            <a href="{% url 'webrepetitor:post_detail' post.id %}">
            <p class="date">{{ post.title }}
            </p>
            {{ post.body|truncatewords_html:30|linebreaks }}
     </h2>


</div>
 {% endfor %}

<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}"> Назад </a>
    {% endif %}
      <span class="current">
    - Часть № {{ page.number }} из {{ page.paginator.num_pages }} -
      </span>
    {% if page.has_next %}

    <a href="?page={{ page.next_page_number }}"> Следующая</a>
    {% endif %}

</div>

{% endblock %}

repetitor/webrepetitor/templates/webrepetitor/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
  </span>
</div>

repetitor/webrepetitor/templates/webrepetitor/predmet.html
{% extends 'webrepetitor/base.html' %}
{% block title %}
    Предметы
{% endblock %}

{% block content %}
<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal text-body-emphasis">Мои предметы</h1>
          {% for el in bbs %}
            <div class="alert alert-warning mt-2">

                      <p class="date">{{ el.title }}
            </p>
            {{ post.body|truncatewords_html:30|linebreaks }}

        </div>
        {% endfor %}
{% endblock %}

repetitor/webrepetitor/templates/webrepetitor/price.html
{% extends 'webrepetitor/base.html' %}
{% block title %}

    Цены
{% endblock %}

{% block content %}

    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal text-body-emphasis">Цены за занятия</h1>
        <p class="fs-5 text-body-secondary"><ya-tr-span data-index="6-0" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="Quickly build an effective pricing table for your potential customers with this Bootstrap example. " data-translation="Качественная подача материала - один из главных факторов для восприятия. " data-ch="0" data-type="trSpan">Качественная подача материала - один из главных факторов для восприятия. </ya-tr-span><ya-tr-span data-index="6-1" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="Постороение занятия с использованием научного подхода к клиенту" data-translation="Постороение занятия с использованием научного подхода к клиенту" data-ch="0" data-type="trSpan">Постороение занятия с использованием научного подхода к клиенту.</ya-tr-span></p>

    {% for el in bbs %}

        <div class="alert alert-warning mt-2">

             <h3>{{ el.price }}</h3>
            <p>Цены указаны за час занятия.</p>
            {{ el.title }}

        </div>
        {% endfor %}
{% endblock %}

repetitor/webrepetitor/templates/webrepetitor/rubrici.html
{% extends "webrepetitor/base.html" %}


{% block title %}Рубрики{% endblock %}

{% block content %}

    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal text-body-emphasis">Рубрики</h1>
      <p class="fs-5 text-body-secondary"><ya-tr-span data-index="6-0" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="Quickly build an effective pricing table for your potential customers with this Bootstrap example. " data-translation="Качественная подача материала - один из главных факторов для восприятия. " data-ch="0" data-type="trSpan">Заключается к применению иновационных подходах к преподаванию. </ya-tr-span><ya-tr-span data-index="6-1" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="Постороение занятия с использованием научного подхода к клиенту" data-translation="Постороение занятия с использованием научного подхода к клиенту" data-ch="0" data-type="trSpan"></ya-tr-span></p>

    {% for post in posts %}

        <div class="alert alert-warning mt-2">
        <p>{{ post.published_time }}<p>

        <p>Дата публикации</p>
    <h2>
            <a href="{% url 'webrepetitor:post_detail' post.id %}">



            <p class="date">{{ post.title }}
            </p>
            {{ post.body|truncatewords_html:30|linebreaks }}
    </h2>

</div>
  {% endfor %}

{% endblock %}

repetitor/webrepetitor/templates/webrepetitor/share.html
{% extends "webrepetitor/base.html" %}
{% load static %}
{% block title %}Контакты{% endblock %}

{% block content %}
<div>
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
 <div class="alert alert-warning mt-2">
  {% if sent %}
    <h1>E-mail Успешно отправлено!</h1>
    <p>
      "{{post.rubric}}" На почтовый адрес: {{ form.cleaned_data.to }}.
    </p>
  {% else %}
     <h1>Телеграмм для связи:</h1>

         <a href="https://t.me/VeronikaIgorevnP"><img src="static/webrepetitor/icons.png" alt="Телеграмм"></a>




    <h1>Моя электронная почта:  </h1>
     <p>start85@mail.ru</p>
    <form method="post" novalidate>
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Отправить сообщение">
    </form>
  <div>
  {% endif %}
{% endblock %}